"""
Per-project Docker runtime image under ``.mcp_terminal/runtime/`` (C-005).

On session open (once per fingerprint): ``docker build`` with a generated Dockerfile
if ``requirements.txt`` exists and inputs changed. Stores ``image_state.json`` with
``image_id`` from ``docker image inspect`` for later verification.

``terminal_run`` uses that local tag when state is valid; rejects stale/missing image.

Author: Vasiliy Zdanovskiy
Email: vasilyvz@gmail.com
"""

from __future__ import annotations

import hashlib
import json
import logging
import shutil
import subprocess
from pathlib import Path
from typing import Any, Dict, Optional, Tuple

logger = logging.getLogger(__name__)

RUNTIME_SUBDIR = Path(".mcp_terminal") / "runtime"
STATE_NAME = "image_state.json"
DOCKERFILE_NAME = "Dockerfile"
# Bump when the generated Dockerfile recipe or build context layout changes.
DOCKERFILE_TEMPLATE_VERSION = "3"

_DOCKERFILE_BODY = """# Generated by mcp_terminal — do not edit. Rebuilt when fingerprint changes.
FROM python:3.12-slim-bookworm
ENV PIP_DISABLE_PIP_VERSION_CHECK=1 \\
    PYTHONDONTWRITEBYTECODE=1
RUN ln -sf /usr/local/bin/python3 /usr/bin/python3 \\
    && ln -sf /usr/local/bin/python3 /usr/bin/python
COPY requirements.txt /tmp/requirements.txt
RUN python -m pip install --upgrade pip setuptools wheel \\
    && pip install --no-cache-dir -r /tmp/requirements.txt
WORKDIR /workspace
"""


def _runtime_dir(project_dir: Path) -> Path:
    return project_dir / RUNTIME_SUBDIR


def _state_path(project_dir: Path) -> Path:
    return _runtime_dir(project_dir) / STATE_NAME


def _dockerfile_path(project_dir: Path) -> Path:
    return _runtime_dir(project_dir) / DOCKERFILE_NAME


def _image_tag(project_id: str) -> str:
    """Stable local tag per project_id (Docker-safe)."""
    h = hashlib.sha256(project_id.strip().lower().encode()).hexdigest()[:12]
    return f"mcp-terminal:pid-{h}"


def runtime_fingerprint(project_dir: Path, *, image_profile: str) -> str:
    """Hash of inputs that define the project runtime image."""
    h = hashlib.sha256()
    h.update(DOCKERFILE_TEMPLATE_VERSION.encode())
    h.update(b"\0")
    h.update(image_profile.encode())
    req = project_dir / "requirements.txt"
    if req.is_file():
        h.update(b"\0")
        h.update(req.read_bytes())
    return h.hexdigest()


def _docker_image_id(image_tag: str) -> Optional[str]:
    try:
        out = subprocess.check_output(
            ["docker", "image", "inspect", image_tag, "--format", "{{.Id}}"],
            text=True,
            stderr=subprocess.DEVNULL,
            timeout=60,
        )
        tid = out.strip()
        return tid or None
    except (subprocess.CalledProcessError, FileNotFoundError, subprocess.TimeoutExpired) as exc:
        logger.debug("docker image inspect %s: %s", image_tag, exc)
        return None


def verify_runtime_image_state(project_dir: Path) -> Tuple[bool, Optional[str]]:
    """Return (ok, reason) comparing ``image_state.json`` to live ``docker image inspect``."""
    sp = _state_path(project_dir)
    if not sp.is_file():
        return False, "no_state"
    try:
        data: Dict[str, Any] = json.loads(sp.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False, "state_corrupt"
    tag = data.get("image_tag")
    expected_id = data.get("image_id")
    if not isinstance(tag, str) or not isinstance(expected_id, str):
        return False, "state_incomplete"
    current = _docker_image_id(tag)
    if current is None:
        return False, "image_missing"
    if current != expected_id:
        return False, "image_id_mismatch"
    return True, None


def resolve_execution_image(
    project_dir: Path,
    *,
    project_id: str,
    image_profile: str,
    stock_image_ref: str,
) -> Tuple[str, Optional[str]]:
    """Pick local project image tag if state valid and fingerprint matches; else stock.

    Returns:
        (image_ref, error_code) where error_code is set when a local state exists but is unusable.
    """
    if not image_profile.startswith("python_"):
        return stock_image_ref, None
    req = project_dir / "requirements.txt"
    if not req.is_file():
        return stock_image_ref, None
    fp_now = runtime_fingerprint(project_dir, image_profile=image_profile)
    sp = _state_path(project_dir)
    if not sp.is_file():
        return stock_image_ref, None
    try:
        data: Dict[str, Any] = json.loads(sp.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return stock_image_ref, "RUNTIME_IMAGE_STATE_CORRUPT"
    if data.get("fingerprint") != fp_now:
        return stock_image_ref, "RUNTIME_IMAGE_STALE"
    tag = data.get("image_tag")
    if not isinstance(tag, str) or not tag:
        return stock_image_ref, "RUNTIME_IMAGE_STATE_INCOMPLETE"
    ok, reason = verify_runtime_image_state(project_dir)
    if not ok:
        code = (
            f"RUNTIME_IMAGE_{reason.upper()}" if reason else "RUNTIME_IMAGE_INVALID"
        )
        return stock_image_ref, code
    return tag, None


def ensure_project_runtime_image(
    project_dir: Path,
    *,
    project_id: str,
    image_profile: str,
    build_timeout_seconds: int = 1200,
) -> Tuple[bool, bool, int, str]:
    """Build or reuse project runtime image. Returns (success, skipped_build, exit_code, detail).

    When ``requirements.txt`` is missing or profile is not Python-based, no-op (skipped).
    """
    if not image_profile.startswith("python_"):
        return True, True, 0, "not_python_profile"
    req = project_dir / "requirements.txt"
    if not req.is_file():
        return True, True, 0, "no_requirements_txt"

    rd = _runtime_dir(project_dir)
    rd.mkdir(parents=True, exist_ok=True)
    _dockerfile_path(project_dir).write_text(_DOCKERFILE_BODY, encoding="utf-8")
    # Minimal build context: only Dockerfile + requirements.txt (not whole project tree).
    shutil.copy2(req, rd / "requirements.txt")

    fp = runtime_fingerprint(project_dir, image_profile=image_profile)
    tag = _image_tag(project_id)
    sp = _state_path(project_dir)
    if sp.is_file():
        try:
            prev = json.loads(sp.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            prev = {}
        if (
            isinstance(prev, dict)
            and prev.get("fingerprint") == fp
            and prev.get("image_tag") == tag
        ):
            ok, _reason = verify_runtime_image_state(project_dir)
            if ok:
                return True, True, 0, "image_verified"

    build_context = rd.resolve()
    cmd = [
        "docker",
        "build",
        "-t",
        tag,
        "-f",
        str(_dockerfile_path(project_dir).resolve()),
        str(build_context),
    ]
    try:
        proc = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=build_timeout_seconds,
        )  # noqa: S603
    except FileNotFoundError:
        return False, False, 127, "docker_not_found"
    except subprocess.TimeoutExpired:
        return False, False, 124, "docker_build_timeout"
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout or "")[-8000:]
        return False, False, proc.returncode, tail

    img_id = _docker_image_id(tag)
    if not img_id:
        return False, False, 1, "inspect_failed_after_build"

    payload = {
        "fingerprint": fp,
        "image_tag": tag,
        "image_id": img_id,
        "image_profile": image_profile,
        "dockerfile_template_version": DOCKERFILE_TEMPLATE_VERSION,
    }
    sp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    return True, False, 0, "built"


def runtime_image_summary(project_dir: Path) -> Optional[Dict[str, Any]]:
    sp = _state_path(project_dir)
    if not sp.is_file():
        return None
    try:
        return json.loads(sp.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
