#!/usr/bin/env python3
"""Generate sudoers fragment for mcp-terminal host execution (used by sync-host-sudo.sh)."""

from __future__ import annotations

import json
import sys
from pathlib import Path


def resolve_path(
    basename: str,
    *,
    command_paths: dict,
    sudo_map: dict,
) -> str | None:
    """Resolve absolute executable path for sudoers.

    Only explicit ``command_paths`` and ``run_as.sudo.*.path`` entries are used.
    Host ``PATH`` / ``which`` is intentionally ignored so install-time sync emits
    container paths from config, not the packaging host's venv or IDE tools.
    """
    key = basename.lower()
    raw = command_paths.get(basename) or command_paths.get(key)
    if isinstance(raw, str) and raw.startswith("/"):
        return raw
    override = sudo_map.get(basename) or sudo_map.get(key)
    if isinstance(override, dict):
        p = override.get("path")
        if isinstance(p, str) and p.startswith("/"):
            return p
    return None


def generate_sudoers_body(config_path: Path, *, enabled_default: bool = True) -> str:
    """Return sudoers file body from term_server.json host_execution section."""
    data = json.loads(config_path.read_text(encoding="utf-8"))
    terminal = data.get("terminal") or {}
    he = terminal.get("host_execution") or {}
    enabled = bool(he.get("enabled")) if enabled_default else False
    service_user = str(he.get("service_user") or "mcp-terminal").strip()
    allowed = [
        str(x).strip()
        for x in (he.get("allowed_commands") or [])
        if isinstance(x, str) and str(x).strip()
    ]
    run_as = he.get("run_as") if isinstance(he.get("run_as"), dict) else {}
    command_paths = run_as.get("command_paths") if isinstance(run_as.get("command_paths"), dict) else {}
    sudo_map = run_as.get("sudo") if isinstance(run_as.get("sudo"), dict) else {}

    invokers: list[str] = []
    for name in (service_user, "root"):
        if name and name not in invokers:
            invokers.append(name)

    lines: list[str] = [
        "# Generated by sync-host-sudo.sh — do not edit manually.",
        f"# Source: {config_path}",
        # visudo-rs (sudo-rs) rejects legacy Defaults:!requiretty; !use_pty allows sudo -n
        # without a TTY in the service container (classic sudo 1.9+ in the image).
    ]
    for invoker in invokers:
        lines.append(f"Defaults:{invoker} !use_pty")

    if not enabled:
        lines.append(f"# host_execution.enabled=false — no sudo grants for {service_user}")
        return "\n".join(lines) + "\n"

    default_paths: list[str] = []
    override_rules: list[str] = []

    for name in allowed:
        path = resolve_path(name, command_paths=command_paths, sudo_map=sudo_map)
        if not path:
            continue
        key = name.lower()
        override = sudo_map.get(name) or sudo_map.get(key)
        if isinstance(override, dict) and override.get("as_user"):
            target = str(override["as_user"]).strip()
            for invoker in invokers:
                override_rules.append(f"{invoker} ALL=({target}) NOPASSWD: {path}")
        else:
            default_paths.append(path)

    for required in ("/bin/bash", "/usr/bin/bash"):
        if Path(required).is_file() and required not in default_paths:
            default_paths.append(required)
            break
    else:
        # Container always has /bin/bash; include for sudoers even if sync runs off-host.
        if "/bin/bash" not in default_paths:
            default_paths.append("/bin/bash")

    if default_paths:
        joined = ", ".join(sorted(set(default_paths)))
        for invoker in reversed(invokers):
            override_rules.insert(0, f"{invoker} ALL=(ALL) NOPASSWD: {joined}")

    if not override_rules:
        lines.append(f"# host_execution enabled but no resolvable command paths for {service_user}")
    else:
        lines.extend(override_rules)

    return "\n".join(lines) + "\n"


def main() -> int:
    if len(sys.argv) != 2:
        print("Usage: sync_host_sudo_lib.py CONFIG.json", file=sys.stderr)
        return 2
    config_path = Path(sys.argv[1])
    if not config_path.is_file():
        print(f"[ERROR] Config not found: {config_path}", file=sys.stderr)
        return 1
    sys.stdout.write(generate_sudoers_body(config_path))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
